# NOTE: These are defaults only.  The values of these keys are maintained by Java Preferences
#       objects, which store key-value pairs in a system-dependent way (Windows uses Registry).
AssembleAll = false
AssembleOnOpen = false
BareMachine = false
DataSegmentHighlighting = true
DelayedBranching = false
DisplayAddressesInHex = true
DisplayValuesInHex = true
EditorCurrentLineHighlighting = true
EditorLineNumbersDisplayed = true
ExtendedAssembler = true
LabelWindowVisibility = false
LoadExceptionHandler = false
ProgramArguments = false
RegistersHighlighting = true
StartAtMain = false
WarningsAreErrors = false
PopupInstructionGuidance = true
EditorPopupPrefixLength = 2
EvenRowBackground = 0x11111B
EvenRowForeground = 0xCDD6F4
OddRowBackground = 0x181825
OddRowForeground = 0xCDD6F4
TextSegmentHighlightBackground = 0xF9E2AF
TextSegmentHighlightForeground = 0x11111B
TextSegmentDelaySlotHighlightBackground = 0xA6E3A1
TextSegmentDelaySlotHighlightForeground = 0x11111B
DataSegmentHighlightBackground = 0x89B4FA
DataSegmentHighlightForeground = 0x11111B
RegisterHighlightBackground = 0xA6E3A1
RegisterHighlightForeground = 0x11111B
DeriveCurrentDirectory = false
