name: Makefile CI

on:
    push:
        branches:
        - next
    pull_request:
        branches:
        - next

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
        -   run: sudo apt-get update && sudo apt-get install openjdk-21-jdk-headless
        -   uses: actions/checkout@v4
        -   run: git fetch origin --tags --unshallow
        -   run: ./build.sh
        -   uses: actions/upload-artifact@v4
            with:
                path: './build/rars.jar'
        -   run: ./test.sh
        -   uses: softprops/action-gh-release@v2
            if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/test-ci'
            with:
                files: rars.jar
                tag_name: 'head'
                make_latest: true
